spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
