name: Check Affected Projects

on:
  workflow_call:
    outputs:
      affected_projects:
        description: 'Si w-backend fue afectado'
        value: ${{ jobs.check.outputs.affected_projects }}

jobs:
  check:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    outputs:
      affected_projects: ${{ steps.affected.outputs.affected_projects }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node & PNPM
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalar PNPM
        run: npm install -g pnpm

      - name: Instalar dependencias
        run: pnpm install

      - name: Detectar proyectos afectados (PR o Push)
        id: affected
        run: |
          set -e

          git fetch origin develop --depth=1

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
          else
            BASE_SHA=$(git merge-base HEAD origin/develop)
          fi

          echo "Usando base SHA: $BASE_SHA"
          AFFECTED=$(npx nx show projects --affected --base=$BASE_SHA --head=HEAD)

          echo "Affected projects:"
          echo "$AFFECTED"

          json_array=$(echo "$AFFECTED" | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "affected_projects=$json_array" >> $GITHUB_OUTPUT
