name: Dependency Check Java

on:
  workflow_call:
    inputs:
      java_version:
        description: 'Java version to use'
        type: number
        required: true
        default: 17

      project_name:
        description: 'Name of the project for SonarQube analysis'
        type: string
        required: true
        # default: 'w-backend'

jobs:
  dependency-check:
    name: Audit Java (OWASP Dependency-Check)
    runs-on: ubuntu-latest
    uses: dependency-check/Dependency-Check_Action@v3
    with:
      project: '${{ inputs.project_name }}'
      scan: './apps/${{ inputs.project_name }}'
      format: 'HTML'
      out: 'reports'
