name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: ['**']

jobs:
  check-affected:
    uses: ./.github/workflows/check-affected.yml
    secrets: inherit

  w-backend:
    needs: check-affected
    if: needs.check-affected.outputs.w_backend_affected == 'true'
    uses: ./.github/workflows/w-backend.yml
    secrets: inherit
