name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: ['**']

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  check-affected:
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/check-affected.yml
    secrets: inherit

  w-backend:
    needs: check-affected
    if: contains(fromJson(needs.check-affected.outputs.affected_projects), 'w-backend')
    uses: ./.github/workflows/w-backend.yml
    secrets: inherit
